[project]
name = "fasstapi-ratelimiting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.1",
    "httpx>=0.28.1",
    "slowapi>=0.1.9",
    "uvicorn>=0.38.0",
]
